-- Human-friendly order numbers: RH-YYMMDD-NNNN  (e.g. RH-260928-0042)
-- Run in Supabase -> SQL Editor after 01-04. Safe to re-run.
--
--   RH      fixed prefix (change it in set_order_number() below if needed)
--   YYMMDD  order date in India time (Asia/Kolkata)
--   NNNN    orders.id, zero-padded to at least 4 digits (grows past 9999 —
--           it is never truncated)
--
-- Because the number is derived from the identity `id` inside a BEFORE INSERT
-- trigger, it is generated by the database itself: no race conditions, no
-- duplicates, and the app code doesn't have to build it.
-- orders.id stays the primary key and order_token stays the secret lookup
-- credential; order_number is only the public, searchable label.

alter table orders add column if not exists order_number text;

create or replace function order_number_for(p_id bigint, p_created timestamptz)
returns text
language sql
immutable
as $$
  select 'RH-'
      || to_char(p_created at time zone 'Asia/Kolkata', 'YYMMDD')
      || '-'
      || lpad(p_id::text, greatest(4, length(p_id::text)), '0');
$$;

create or replace function set_order_number()
returns trigger
language plpgsql
as $$
begin
  new.order_number := order_number_for(new.id, coalesce(new.created_at, now()));
  return new;
end;
$$;

drop trigger if exists trg_set_order_number on orders;
create trigger trg_set_order_number
  before insert on orders
  for each row execute function set_order_number();

-- Backfill existing orders (no-op on a fresh database).
update orders
   set order_number = order_number_for(id, created_at)
 where order_number is null;

alter table orders alter column order_number set not null;

-- text_pattern_ops makes both exact lookups (= 'RH-260928-0042') and prefix
-- filters (LIKE 'RH-2609%' for a whole month) use the index.
create unique index if not exists idx_orders_order_number
  on orders (order_number text_pattern_ops);
